In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv('SubtaskB_test_Ire.csv').drop(columns=['Id']).rename(columns={'topic': 'Annotator_1'})
df2 = pd.read_csv('subtaskB_test_marti.csv').drop(columns=['Id']).rename(columns={'conspiracy': 'Annotator_2'})
df3 = pd.read_csv('subtaskB_clean_test_cased_labeled_Elena.csv', sep=';').rename(columns={'label': 'Annotator_3'})

## aligning

In [5]:
df1 = df1.fillna('Covid')
df1['Annotator_1'].unique()

array(['Terra Piatta', 'Covid', 'Russia', 'Qanon', '???', 'Russia/UFO?',
       'Terra Piatta/sbarco sulla luna???', 'Covid???', '??? UFO?',
       'Russia???', '???UFO', 'UFO???', 'Qanon???'], dtype=object)

In [6]:
df2['Annotator_2'].unique()

array(['Terra Piatta', 'Covid', 'Russia', 'Qanon'], dtype=object)

In [7]:
df3['Annotator_3'].unique()

array([3, 1, 2, 0, 4])

In [74]:
df3.query('Annotator_3 == 4')

comment_text  Annotator_3
152  Incubo alimentari: in Germania aumenti fino al...            4
187  In Canada è in corso da due giorni una movimen...            4
191  Ora ho visto che qualcuno ediuca si accorge.. ...            4
242  Se è così che si vota , in modo chiaro e limpi...            4
268  ( Sieni   TUTTO  LUE stringe le maglie sulla l...            4

In [8]:
for i, row in df1.iterrows():
  if row['Annotator_1'] == '???':
    df1.loc[i, 'Annotator_1'] = 'Covid'
  elif row['Annotator_1'] == 'Russia/UFO?' or row['Annotator_1'] == 'Russia???':
    df1.loc[i, 'Annotator_1'] = 'Russia'

  elif row['Annotator_1'] == 'Terra Piatta/sbarco sulla luna???':
    df1.loc[i, 'Annotator_1'] = 'Terra Piatta'

  elif row['Annotator_1'] == 'Qanon???':
    df1.loc[i, 'Annotator_1'] = 'Qanon'

  elif row['Annotator_1'] == 'Covid???':
    df1.loc[i, 'Annotator_1'] = 'Covid'

  elif row['Annotator_1'] == '??? UFO?' or row['Annotator_1'] == 'UFO???' or row['Annotator_1'] == '???UFO':
    df1.loc[i, 'Annotator_1'] = 'Terra Piatta'

for i, row in df3.iterrows():
    if row['Annotator_3'] == 4:
      df3.loc[i, 'Annotator_3'] = 0

In [87]:
np.unique(df3['Annotator_3'], return_counts=True)

(array([0, 1, 2, 3]), array([ 76, 162,  22,  40]))

In [9]:
df1['Annotator_1'].unique()

array(['Terra Piatta', 'Covid', 'Russia', 'Qanon'], dtype=object)

In [10]:
def encode(df, col, label_dict):
  for i,row in df.iterrows():
    val = label_dict[row[col]]
    df.loc[i, col] = val
  return df


In [11]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   comment_text  300 non-null    object
 1   Annotator_1   300 non-null    object
dtypes: object(2)
memory usage: 4.8+ KB


In [13]:
 label2id = {
    "Qanon": 0,
    "Covid": 1,
    "Terra Piatta": 2,
    "Russia": 3
}

In [15]:
for i,row in df1.iterrows():
    val = label2id[row['Annotator_1']]
    df1.loc[i, 'Annotator_1'] = val

In [17]:
df2 = encode(df2, 'Annotator_2', label2id)

In [18]:
df1['Annotator_1'].unique()

array([2, 1, 3, 0], dtype=object)

In [19]:
df2['Annotator_2'].unique()

array([2, 1, 3, 0], dtype=object)

In [20]:
df = df1.copy()
df['Annotator_2'] = df2['Annotator_2']
df['Annotator_3'] = df3['Annotator_3']

In [21]:
df.head()

comment_text Annotator_1 Annotator_2  \
0  Ho fatto delle foto aeree ad una quota di circ...           2           2   
1  Prof. Bellavite: tantissime persone costrette ...           1           1   
2    Ma si allontana....  su una terra PIATTA,......           2           2   
3  Non tutti gli Ukraini sono contro la Russia.\n...           3           3   
4  Non opinioni ma dati.\n\nUno strepitoso **Giov...           1           1   

   Annotator_3  
0            3  
1            1  
2            3  
3            2  
4            1

In [22]:
df.shape

(300, 4)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   comment_text  300 non-null    object
 1   Annotator_1   300 non-null    object
 2   Annotator_2   300 non-null    object
 3   Annotator_3   300 non-null    int64 
dtypes: int64(1), object(3)
memory usage: 9.5+ KB


## random perturbation (per cotrollare che le funzioni funonziano)

non runnare on actual data

In [233]:
# random perturbation (valori legali)
for i in range(500):
  df.loc[np.random.randint(df.shape[0]+1), 'Annotator_1'] = np.random.randint(0,4, dtype=np.int64)
  df.loc[np.random.randint(df.shape[0]+1), 'Annotator_2'] = np.random.randint(0,4, dtype=np.int64)
  df.loc[np.random.randint(df.shape[0]+1), 'Annotator_3'] = np.random.randint(0,4, dtype=np.int64)

In [234]:
df.head()

comment_text  Annotator_1  \
0  Siamo davanti ad una prova, e non solo di quoz...          2.0   
1  La storia dei 2 bimbi di Bergamo - vaccini: qu...          0.0   
2  L'avete capito che non toglieranno il green pa...          3.0   
3  Quindi  la farsa dello spazio e della terra a ...          3.0   
4  In breve tempo, per accedere a Internet, sarà ...          1.0   

   Annotator_2  Annotator_3  
0          1.0          1.0  
1          0.0          1.0  
2          0.0          1.0  
3          3.0          1.0  
4          0.0          1.0

In [235]:
# random perturbation (valori non legali)
for i in range(11):
  df.loc[np.random.randint(df.shape[0]+1), 'Annotator_1'] = np.random.randint(4,5, dtype=np.int64)
  df.loc[np.random.randint(df.shape[0]+1), 'Annotator_2'] = np.random.randint(4,5, dtype=np.int64)
  df.loc[np.random.randint(df.shape[0]+1), 'Annotator_3'] = np.random.randint(4,5, dtype=np.int64)

In [24]:
for col in df.columns[1:]:
  df[col] =pd.to_numeric(df[col], errors='coerce').fillna(0).astype('int64').astype(np.int64)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   comment_text  300 non-null    object
 1   Annotator_1   300 non-null    int64 
 2   Annotator_2   300 non-null    int64 
 3   Annotator_3   300 non-null    int64 
dtypes: int64(3), object(1)
memory usage: 9.5+ KB


# Cleaning

In [26]:
def check_vals(unique_vals_exp, df, columns, return_dict=False):
  idxs = dict()
  for col in df.columns[1:]:
    unique_vals = np.unique(df[col])
    if not np.array_equal(unique_vals, unique_vals_exp):
      print('Errors found in col', col)
      print('Indexes of errors:', list(df.query(f'{col} not in {unique_vals_exp}').index))
      idxs[col] = list(df.query(f'{col} not in {unique_vals_exp}').index)

  if len(idxs) == 0:
      print('no errors found')

  if return_dict:
    return idxs

In [27]:
unique_vals_exp = [0,1,2,3]
check_vals(unique_vals_exp, df, df.columns[1:])

no errors found


In [242]:
idx_dict = check_vals(unique_vals_exp, df, df.columns[1:], return_dict=True)
for col, idx in idx_dict.items():
  df.loc[idx, col] = 1

Errors found in col Annotator_1
Indexes of errors: [30, 57, 225, 481, 501, 525, 562, 594, 630, 731, 769]
Errors found in col Annotator_2
Indexes of errors: [159, 301, 365, 419, 435, 501, 540, 615, 647, 668, 712]
Errors found in col Annotator_3
Indexes of errors: [20, 121, 205, 402, 437, 445, 500, 578, 594, 663, 698]


In [243]:
check_vals(unique_vals_exp, df, df.columns[1:])

no errors found


# Gold Standard

In [40]:
df['Gold_Standard'] = 42
for idx ,row in df[['Annotator_1','Annotator_2','Annotator_3']].iterrows():
  vals = np.array([row['Annotator_1'], row['Annotator_2'], row['Annotator_3']])
  if len(np.unique(vals)) == 2:
    df.loc[idx, 'Gold_Standard'] = np.argmax(np.bincount(vals))

to_check = list(df.query('Gold_Standard == 42').index)
 # indice records in cui ogni annotatore ha etichettato con etuchette differenti
print('Records to check:', len(to_check))

ratio = len(to_check)/len(df['Annotator_1'])
if ratio > 0.5:
  print(f'Cioè il {round(ratio*100)}% a facc ro cazz')

Records to check: 193
Cioè il 64% a facc ro cazz


# Inter-annotator agreement

### **K = P(A) - P(E) / 1 - P(E)**

P(A) = Volte in cui gli annotatori si sono mostrati d'accordo

P(E) = Volte in cui ci si aspetta che gli annotatori per caso compiano la stessa scelta (e = expected)

The higher the better

In [32]:
def interannotator_agreement(annotator1, annotator2):
  num_records = len(annotator1)
  label1, label2, label3, label4 = np.unique(annotator1)

  counts1 = np.unique(annotator1, return_counts=True)[1]
  counts2 = np.unique(annotator2, return_counts=True)[1]

  annotation_prob = {
      'Annotator_1': {
          label1: counts1[0]/num_records,
          label2: counts1[1]/num_records,
          label3: counts1[2]/num_records,
          label4: counts1[3]/num_records
      },
      'Annotator_2': {
          label1: counts2[0]/num_records,
          label2: counts2[1]/num_records,
          label3: counts2[2]/num_records,
          label4: counts2[3]/num_records
      }
  }

  alignment = 0

  for val1, val2 in zip(annotator1, annotator2):
    if val1 == val2:
      alignment += 1

  p_a = alignment/num_records
  p_e = (annotation_prob['Annotator_1'][label1] * annotation_prob['Annotator_2'][label1]) + \
        (annotation_prob['Annotator_1'][label2] * annotation_prob['Annotator_2'][label2]) + \
        (annotation_prob['Annotator_1'][label3] * annotation_prob['Annotator_2'][label3]) + \
        (annotation_prob['Annotator_1'][label4] * annotation_prob['Annotator_2'][label4])

  k =  (p_a - p_e) / (1 - p_e)

  return k

#print(interannotator_agreement(np.array([1,1,1,2,2,3,4,4]), np.array([1,1,1,2,2,3,4,4])))



1.0


In [33]:
from statistics import harmonic_mean, mean

k1 = interannotator_agreement(np.array(df['Annotator_1']), np.array(df['Annotator_2']))
k2 = interannotator_agreement(np.array(df['Annotator_1']), np.array(df['Annotator_3']))
k3 = interannotator_agreement(np.array(df['Annotator_2']), np.array(df['Annotator_3']))
agg = (k1+k2+k3)/3

print('k1:', k1)
print('k2:', k2)
print('k3:', k3)
print('Mean:', agg)



k1: 0.8058645096056622
k2: 0.4277777777777777
k3: 0.368016120168529
Mean: 0.5338861358506563
